In [1]:
# pytorch has built in differetiation engine called torch.autograd which is used to compute gradients 
# for backpropagation

In [13]:
import torch

x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

In [14]:
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")


Gradient function for z = <AddBackward0 object at 0x7f5bc9c10be0>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x7f5bc9c10fa0>


In [15]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.0562, 0.2146, 0.2483],
        [0.0562, 0.2146, 0.2483],
        [0.0562, 0.2146, 0.2483],
        [0.0562, 0.2146, 0.2483],
        [0.0562, 0.2146, 0.2483]])
tensor([0.0562, 0.2146, 0.2483])


In [18]:
# by default, all tensors with requires_grad=True are tracking their computaional history
# and support gradient computaion, but we dont need it for just forward pass after trainign 
# stop tracking with torch.no_grad() block

z = torch.matmul(x, w)+b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x, w)+b
print(z.requires_grad)

#another way to do it is detach() method
z = torch.matmul(x, w)+b
z_det = z.detach()
print(z_det.requires_grad)

True
False
False


In [19]:
# tensor gradients and jacobian products
# we jacobian product if output funciton is an arbitary tensor

inp=torch.eye(4,5,requires_grad=True)
out = (inp+1).pow(2).t()
out.backward(torch.ones_like(out), retain_graph=True)
print(f"First call\n{inp.grad}")
'''
out.backward(torch.ones_like(out), retain_graph=True)
print(f"\nSecond call\n{inp.grad}")
inp.grad.zero_()
out.backward(torch.ones_like(out), retain_graph=True)
print(f"\nCall after zeroing gradients\n{inp.grad}") '''

First call
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])


'\nout.backward(torch.ones_like(out), retain_graph=True)\nprint(f"\nSecond call\n{inp.grad}")\ninp.grad.zero_()\nout.backward(torch.ones_like(out), retain_graph=True)\nprint(f"\nCall after zeroing gradients\n{inp.grad}") '