In [3]:
import torch
import numpy as np

In [4]:
# tensor can be initialised  in multiple ways
# directly from data
data=[[1,2],[3,4]]
x_data=torch.tensor(data)

#from a numpy array
np_array = np.array(data)
x_np=torch.from_numpy(np_array)


In [5]:
# anoter rensor
# the new tensor retaisn the properties (shape,datatype) of the argument tensor
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")


Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.1994, 0.7507],
        [0.4002, 0.7385]]) 



In [6]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0750, 0.1587, 0.1827],
        [0.2321, 0.9813, 0.1801]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
# tensor attributes
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [8]:
#tensor Operations
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [12]:
#standard numpy like indexing and slicing

tensor=torch.ones(4,4)
tensor[:,0]=0
print(tensor)

0


In [18]:
#joining tensors
shape=(3,3,)
tensor1 = torch.rand(shape)
tensor2 = torch.rand(shape)

print(tensor1)
print(tensor2)


tensor_sum= torch.cat([tensor1,tensor2],dim=0)

print(tensor_sum)




tensor([[0.7890, 0.7940, 0.8316],
        [0.1300, 0.2118, 0.9614],
        [0.9312, 0.3941, 0.9896]])
tensor([[0.7829, 0.5669, 0.6930],
        [0.5202, 0.5000, 0.2232],
        [0.2422, 0.3132, 0.7330]])
tensor([[0.7890, 0.7940, 0.8316],
        [0.1300, 0.2118, 0.9614],
        [0.9312, 0.3941, 0.9896],
        [0.7829, 0.5669, 0.6930],
        [0.5202, 0.5000, 0.2232],
        [0.2422, 0.3132, 0.7330]])


In [20]:
#multiplying tensors
# This computes the element-wise product
tensor=torch.rand(shape)
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")


tensor.mul(tensor) 
 tensor([[0.1334, 0.0577, 0.4904],
        [0.1052, 0.1339, 0.4499],
        [0.2849, 0.0493, 0.5771]]) 

tensor * tensor 
 tensor([[0.1334, 0.0577, 0.4904],
        [0.1052, 0.1339, 0.4499],
        [0.2849, 0.0493, 0.5771]])


In [21]:
tensor=torch.rand(shape)

#matrix multiplication
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[1.4446, 1.0985, 1.5176],
        [1.0985, 1.3732, 1.7439],
        [1.5176, 1.7439, 2.2418]]) 

tensor @ tensor.T 
 tensor([[1.4446, 1.0985, 1.5176],
        [1.0985, 1.3732, 1.7439],
        [1.5176, 1.7439, 2.2418]])


In [23]:
tensor=torch.ones(4,4)
tensor[:,1]=0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [24]:
# in-place operations
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [27]:
#bridge with numpy
#Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [28]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [29]:
n = np.ones(5)
t = torch.from_numpy(n)